### ISSUE TITLE
[Bug] Titles being translated to french instead of selected language

### ISSUE THREAD

**Issue by lucastwg** [vlourme/yahoo-auction-alert-discord-bot#2]
target_language is set as "en" in easygoogletranslate, but titles displayed in discord appear in french.

![imagen](https://github.com/vlourme/yahoo-auction-alert-discord-bot/assets/57829093/c40db88d-5e83-4d9f-9e6e-b67d5d9f68a1)
![imagen](https://github.com/vlourme/yahoo-auction-alert-discord-bot/assets/57829093/720e869a-d199-4546-ab07-400f5b24bd29)

I believe this can be easily fixed by changing the language in the unofficial api link in both mercari.py and yahoo.py

![imagen](https://github.com/vlourme/yahoo-auction-alert-discord-bot/assets/57829093/0f183f1b-edbe-4c48-a57e-f25b68cc2d73)

**Comment by vlourme** [comment]
Changing to `/en/` from `/fr/` URL seems to fix the issue, as you said.
Feel free to re-open the issue if it still happens :)
